
server {

    listen 80;

    return 301 https://$host$request_uri;

}



server {

    listen 443 ssl;

    ssl_certificate     /etc/test-secret/tls.crt;

    ssl_certificate_key /etc/test-secret/tls.key;



    location / {

        root /usr/share/nginx/html;

        index index.html;

    }

}

